apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: <your-docker-registry>/main-image:latest
        imagePullPolicy: Always
        env:
        - name: LAYER_CONTROLLER_URL
          value: "http://layer-controller-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: main
spec:
  selector:
    app: main
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
