---
- name: download & install Helm
  ansible.builtin.get_url:
    url: "{{ helm_get_url }}"
    dest: "/home/{{ kube_user }}/.ansible/tmp/{{ helm_script }}"
    mode: '0700'

- name: run Helm script
  ansible.builtin.shell: "./{{ helm_script }}"
  args:
    chdir: "/home/{{ kube_user }}/.ansible/tmp"

- name: add NVIDIA Helm Repo
  ansible.builtin.shell: >
    helm repo add {{ nvidia_repo_name }} {{ nvidia_repo_url }}

- name: update Helm Repo
  ansible.builtin.shell: helm repo update

- name: install GPU Operator
  ansible.builtin.shell: >
    helm install --wait --generate-name
    -n {{ gpu_operator_namespace }} --create-namespace
    {{ gpu_operator_chart }} --version {{ gpu_operator_version }}
    --kubeconfig /home/{{ kube_user }}/.kube/config