- name: Remove any old dockerlist
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Remove any old k8slist
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: delete old Docker / containerd packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes
    autoremove: yes

- name: update apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisites for Docker repo
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: ensure /etc/apt/keyrings exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download Docker GPG to keyrings
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture == 'aarch64' and 'arm64' or 'amd64' }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }} stable
    filename: docker

- name: update apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install Docker CE & containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: start and enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes

- name: ensure /etc/apt/keyrings exists for Kubernetes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and dearmor Kubernetes GPG key
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key \
      | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    executable: /bin/bash

- name: Add Kubernetes APT repository
  become: true
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    state: present

- name: update apt cache (Kubernetes)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install kubelet, kubeadm, kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: hold kubelet, kubeadm, kubectl at current version
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl
